/**
 * Field — a labelled control with its description and error message.
 *
 * The ids that tie the three together are generated by `Field` and read from
 * context, so the caller never wires `htmlFor` or `aria-describedby` by hand:
 *
 *   <Field invalid={Boolean(error)}>
 *     <FieldLabel>Volume label</FieldLabel>
 *     <TextInput value={name} onInput={…} />
 *     <FieldDescription>Up to eleven characters.</FieldDescription>
 *   </Field>
 *
 * When `invalid` is set the control points at the error instead of the
 * description, so a screen reader reads the problem rather than the hint.
 */
import type { ComponentProps, SyntheticEvent } from "yract";
import { useContext, useId } from "yract";
import { FieldContext } from "./contexts";

export interface FieldProps extends ComponentProps<"div"> {
  invalid?: boolean;
}

export function* Field({ invalid = false, children, ...rest }: FieldProps) {
  const controlId = yield* useId();
  const descriptionId = yield* useId();
  const errorId = yield* useId();

  return (
    <FieldContext value={{ controlId, descriptionId, errorId, invalid }}>
      <div {...rest} className="dos-field">
        {children}
      </div>
    </FieldContext>
  );
}

export function* FieldLabel({ children, ...rest }: ComponentProps<"label">) {
  const { controlId } = yield* useContext(FieldContext);
  return (
    <label {...rest} className="dos-label" htmlFor={controlId}>
      {children}
    </label>
  );
}

export function* FieldDescription({ children, ...rest }: ComponentProps<"p">) {
  const { descriptionId } = yield* useContext(FieldContext);
  return (
    <p {...rest} className="dos-desc" id={descriptionId}>
      {children}
    </p>
  );
}

function describedBy(invalid: boolean, descriptionId: string, errorId: string): string {
  return invalid ? errorId : descriptionId;
}

export interface TextInputProps extends ComponentProps<"input"> {
  value: string;
  /**
   * Receives the new value, not the DOM event — the control unwraps it.
   * Named apart from the native `onChange`, which still passes through.
   */
  onValueChange?: (value: string) => void;
  type?: "text" | "email" | "password" | "search" | "tel" | "url";
}

export function* TextInput({ value, onValueChange, type = "text", ...rest }: TextInputProps) {
  const { controlId, descriptionId, errorId, invalid } = yield* useContext(FieldContext);
  return (
    <input
      {...rest}
      className="dos-input"
      id={controlId}
      type={type}
      value={value}
      aria-invalid={invalid ? "true" : undefined}
      aria-describedby={describedBy(invalid, descriptionId, errorId)}
      onInput={(event: SyntheticEvent<Event, HTMLInputElement>) => {
        onValueChange?.(event.currentTarget?.value ?? "");
      }}
    />
  );
}

export interface SelectProps extends ComponentProps<"select"> {
  value: string;
  /** Receives the new value. The native `onChange` still passes through. */
  onValueChange?: (value: string) => void;
}

/**
 * Native select behind a drawn arrow, so the platform picker still opens.
 * Rest props land on the `<select>`, not the presentational wrapper — that is
 * the element a caller means when passing `aria-labelledby` or `disabled`.
 */
export function* Select({ value, onValueChange, children, ...rest }: SelectProps) {
  const { controlId, descriptionId, errorId, invalid } = yield* useContext(FieldContext);
  return (
    <div className="dos-select-wrap">
      <select
        {...rest}
        className="dos-select"
        id={controlId}
        value={value}
        aria-describedby={describedBy(invalid, descriptionId, errorId)}
        onChange={(event: SyntheticEvent<Event, HTMLSelectElement>) =>
          onValueChange?.(event.currentTarget?.value ?? "")
        }
      >
        {children}
      </select>
    </div>
  );
}

export interface RangeProps extends ComponentProps<"input"> {
  value: number;
  min: number;
  max: number;
  step?: number;
  /** Receives the new value. The native `onChange` still passes through. */
  onValueChange?: (value: number) => void;
}

/**
 * Set `aria-valuetext` when the number needs a unit — without it a screen
 * reader announces a bare number and the listener never learns what it counts.
 */
export function* Range({ value, min, max, step = 1, onValueChange, ...rest }: RangeProps) {
  const { controlId, descriptionId, errorId, invalid } = yield* useContext(FieldContext);
  return (
    <input
      aria-describedby={describedBy(invalid, descriptionId, errorId)}
      {...rest}
      className="dos-range"
      id={controlId}
      type="range"
      value={String(value)}
      min={String(min)}
      max={String(max)}
      step={String(step)}
      onInput={(event: SyntheticEvent<Event, HTMLInputElement>) =>
        onValueChange?.(Number(event.currentTarget?.value ?? min))
      }
    />
  );
}
