/**
 * Field — a labelled control with its description.
 *
 * The ids that tie them together are generated by `Field` and read from
 * context, so the caller never wires `htmlFor` or `aria-describedby` by hand.
 */
import { use, useId } from "react";
import type { ChangeEvent, ComponentProps, ReactNode } from "react";
import { FieldContext } from "./contexts";

export interface FieldProps extends ComponentProps<"div"> {
  invalid?: boolean;
  children?: ReactNode;
}

export function Field({ invalid = false, children, ...rest }: FieldProps) {
  const controlId = useId();
  const descriptionId = useId();
  const errorId = useId();

  return (
    <FieldContext value={{ controlId, descriptionId, errorId, invalid }}>
      <div {...rest} className="dos-field">
        {children}
      </div>
    </FieldContext>
  );
}

export function FieldLabel({ children, ...rest }: ComponentProps<"label">) {
  const { controlId } = use(FieldContext);
  return (
    <label {...rest} className="dos-label" htmlFor={controlId}>
      {children}
    </label>
  );
}

export function FieldDescription({ children, ...rest }: ComponentProps<"p">) {
  const { descriptionId } = use(FieldContext);
  return (
    <p {...rest} className="dos-desc" id={descriptionId}>
      {children}
    </p>
  );
}

function describedBy(invalid: boolean, descriptionId: string, errorId: string): string {
  return invalid ? errorId : descriptionId;
}

export interface TextInputProps extends Omit<ComponentProps<"input">, "onChange" | "value"> {
  value: string;
  /** Receives the new value, not the DOM event — the control unwraps it. */
  onValueChange?: (value: string) => void;
  type?: "text" | "email" | "password" | "search" | "tel" | "url";
}

export function TextInput({ value, onValueChange, type = "text", ...rest }: TextInputProps) {
  const { controlId, descriptionId, errorId, invalid } = use(FieldContext);
  return (
    <input
      {...rest}
      className="dos-input"
      id={controlId}
      type={type}
      value={value}
      aria-invalid={invalid ? "true" : undefined}
      aria-describedby={describedBy(invalid, descriptionId, errorId)}
      onChange={(event: ChangeEvent<HTMLInputElement>) => onValueChange?.(event.target.value)}
    />
  );
}

export interface SelectProps extends Omit<ComponentProps<"select">, "onChange" | "value"> {
  value: string;
  onValueChange?: (value: string) => void;
}

/**
 * Native select behind a drawn arrow, so the platform picker still opens.
 * Rest props land on the `<select>`, not the presentational wrapper — that is
 * the element a caller means when passing `aria-labelledby` or `disabled`.
 */
export function Select({ value, onValueChange, children, ...rest }: SelectProps) {
  const { controlId, descriptionId, errorId, invalid } = use(FieldContext);
  return (
    <div className="dos-select-wrap">
      <select
        {...rest}
        className="dos-select"
        id={controlId}
        value={value}
        aria-describedby={describedBy(invalid, descriptionId, errorId)}
        onChange={(event: ChangeEvent<HTMLSelectElement>) => onValueChange?.(event.target.value)}
      >
        {children}
      </select>
    </div>
  );
}

export interface RangeProps extends Omit<ComponentProps<"input">, "onChange" | "value"> {
  value: number;
  min: number;
  max: number;
  step?: number;
  onValueChange?: (value: number) => void;
}

export function Range({ value, min, max, step = 1, onValueChange, ...rest }: RangeProps) {
  const { controlId, descriptionId, errorId, invalid } = use(FieldContext);
  return (
    <input
      aria-describedby={describedBy(invalid, descriptionId, errorId)}
      {...rest}
      className="dos-range"
      id={controlId}
      type="range"
      value={String(value)}
      min={String(min)}
      max={String(max)}
      step={String(step)}
      onChange={(event: ChangeEvent<HTMLInputElement>) =>
        onValueChange?.(Number(event.target.value))
      }
    />
  );
}
